import { LegoSet } from './types';

export const LEGO_SETS: LegoSet[] = [
  {
    id: "75192",
    name: "UCS Millennium Falcon",
    year: 2017,
    theme: "Star Wars",
    piece_count: 7541,
    minifigure_count: 10,
    hint: "This giant set belongs to the prestigious Ultimate Collector Series and is one of the largest ever released.",
    colorTheme: "bg-slate-300 border-slate-400",
    imagePrompt: "starship"
  },
  {
    id: "75252",
    name: "Imperial Star Destroyer",
    year: 2019,
    theme: "Star Wars",
    piece_count: 4784,
    minifigure_count: 2,
    hint: "A massive, wedge-shaped grey capital ship from the Galactic Empire, part of the UCS collection.",
    colorTheme: "bg-slate-400 border-slate-500",
    imagePrompt: "wedge"
  },
  {
    id: "10294",
    name: "Titanic",
    year: 2021,
    theme: "Icons",
    piece_count: 9090,
    minifigure_count: 0,
    hint: "A highly-detailed historical scale replica of the ocean liner that tragically sank in 1912.",
    colorTheme: "bg-[#252525] border-stone-800",
    imagePrompt: "ship"
  },
  {
    id: "10307",
    name: "Eiffel Tower",
    year: 2022,
    theme: "Icons",
    piece_count: 10001,
    minifigure_count: 0,
    hint: "At 149 cm tall, this tower is the tallest standard LEGO set ever released, set in beautiful gray truss-work.",
    colorTheme: "bg-zinc-300 border-zinc-400",
    imagePrompt: "tower"
  },
  {
    id: "71043",
    name: "Hogwarts Castle",
    year: 2018,
    theme: "Harry Potter",
    piece_count: 6020,
    minifigure_count: 4,
    hint: "This microscale architectural masterpiece representing the magical boarding school contains hundreds of mystery elements.",
    colorTheme: "bg-amber-100 border-amber-200",
    imagePrompt: "castle"
  },
  {
    id: "76178",
    name: "Daily Bugle",
    year: 2021,
    theme: "Marvel",
    piece_count: 3772,
    minifigure_count: 25,
    hint: "This towering newspaper office skyscraper set contains the ultimate list of Spider-Man characters.",
    colorTheme: "bg-sky-100 border-sky-300",
    imagePrompt: "skyscraper"
  },
  {
    id: "10305",
    name: "Lion Knights' Castle",
    year: 2022,
    theme: "Icons",
    piece_count: 4514,
    minifigure_count: 22,
    hint: "This 90th-anniversary fantasy castle set features a functional drawbridge, armory, watermill, and classic medieval designs.",
    colorTheme: "bg-zinc-200 border-zinc-400",
    imagePrompt: "castle"
  },
  {
    id: "21322",
    name: "Pirates of Barracuda Bay",
    year: 2020,
    theme: "Ideas",
    piece_count: 2545,
    minifigure_count: 8,
    hint: "This pirate shipwreck island can be converted back and forth into an active, ocean-going pirate ship.",
    colorTheme: "bg-amber-800 border-amber-900",
    imagePrompt: "pirate_ship"
  },
  {
    id: "10281",
    name: "Bonsai Tree",
    year: 2021,
    theme: "Botanical Collection",
    piece_count: 878,
    minifigure_count: 0,
    hint: "Comes with interchangeable leaves—vibrant green leaves or delightful pink cherry blossoms made of tiny frogs.",
    colorTheme: "bg-emerald-800 border-emerald-950",
    imagePrompt: "tree"
  },
  {
    id: "42115",
    name: "Lamborghini Sián FKP 37",
    year: 2020,
    theme: "Technic",
    piece_count: 3696,
    minifigure_count: 0,
    hint: "A magnificent lime-green Italian supercar constructed in complex gearboxes, with functional scissor doors.",
    colorTheme: "bg-lime-500 border-lime-600",
    imagePrompt: "car"
  },
  {
    id: "71374",
    name: "Nintendo Entertainment System",
    year: 2020,
    theme: "Super Mario",
    piece_count: 2646,
    minifigure_count: 0,
    hint: "Contains a vintage television with a nostalgic rolling screen and a realistic retro gaming console model.",
    colorTheme: "bg-neutral-300 border-neutral-400",
    imagePrompt: "console"
  },
  {
    id: "10497",
    name: "Galaxy Explorer",
    year: 2022,
    theme: "Icons",
    piece_count: 1254,
    minifigure_count: 4,
    hint: "This nostalgic blue, white and trans-yellow starship is a 90th-anniversary tribute to classic 1970s Space sets.",
    colorTheme: "bg-blue-600 border-blue-700",
    imagePrompt: "spaceship"
  },
  {
    id: "21319",
    name: "Central Perk",
    year: 2019,
    theme: "Ideas",
    piece_count: 1070,
    minifigure_count: 7,
    hint: "Recreate the iconic New York coffee shop set from the legendary TV series Friends.",
    colorTheme: "bg-teal-700 border-teal-800",
    imagePrompt: "sofa"
  },
  {
    id: "75308",
    name: "R2-D2",
    year: 2021,
    theme: "Star Wars",
    piece_count: 2314,
    minifigure_count: 1,
    hint: "Build a highly articulated brick astromech droid with a retractable third leg and turning dome, including a hidden lightsaber.",
    colorTheme: "bg-slate-100 border-slate-300",
    imagePrompt: "droid"
  },
  {
    id: "10316",
    name: "The Lord of the Rings: Rivendell",
    year: 2023,
    theme: "Icons",
    piece_count: 6167,
    minifigure_count: 15,
    hint: "Recreate the legendary elven sanctuary, complete with the Council Ring, Frodo's study, and breathtaking foliage colors.",
    colorTheme: "bg-green-100 border-green-200",
    imagePrompt: "temple"
  },
  {
    id: "76269",
    name: "Avengers Tower",
    year: 2023,
    theme: "Marvel",
    piece_count: 5201,
    minifigure_count: 31,
    hint: "A soaring steel-blue skyscraper that captures the headquarters of Earth's Mightiest Heroes from the MCU.",
    colorTheme: "bg-cyan-900 border-cyan-950",
    imagePrompt: "skyscraper"
  },
  {
    id: "21330",
    name: "Home Alone",
    year: 2021,
    theme: "Ideas",
    piece_count: 3955,
    minifigure_count: 5,
    hint: "Recreate the McCallister family house, filled with Kevin's creative traps from the holiday classic.",
    colorTheme: "bg-[#7c2d12] border-amber-950",
    imagePrompt: "house"
  },
  {
    id: "10302",
    name: "Optimus Prime",
    year: 2022,
    theme: "Icons",
    piece_count: 1508,
    minifigure_count: 0,
    hint: "A red and blue robotic leader that can seamlessly transform into an awesome semi-truck without being rebuilt.",
    colorTheme: "bg-red-600 border-blue-600",
    imagePrompt: "robot"
  },
  {
    id: "10261",
    name: "Roller Coaster",
    year: 2018,
    theme: "Creator Expert",
    piece_count: 4124,
    minifigure_count: 11,
    hint: "This massive red track set features a fully functional chain-link elevator of coaster train thrill rides.",
    colorTheme: "bg-red-500 border-yellow-500",
    imagePrompt: "tracks"
  },
  {
    id: "10320",
    name: "Eldorado Fortress",
    year: 2023,
    theme: "Icons",
    piece_count: 2509,
    minifigure_count: 8,
    hint: "A stunning white brick fort tribute celebrating vintage 1980s Pirate themes with real firing cannons.",
    colorTheme: "bg-[#eceeef] border-slate-300",
    imagePrompt: "castle"
  },
  {
    id: "71741",
    name: "NINJAGO City Gardens",
    year: 2021,
    theme: "Ninjago",
    piece_count: 5685,
    minifigure_count: 19,
    hint: "A magnificent five-tier vertical garden building displaying gorgeous neon banners and dynamic architecture.",
    colorTheme: "bg-purple-600 border-purple-700",
    imagePrompt: "pagoda"
  },
  {
    id: "10220",
    name: "Volkswagen T1 Camper Van",
    year: 2011,
    theme: "Creator Expert",
    piece_count: 1334,
    minifigure_count: 0,
    hint: "Classic split-screen retro red camper van with detailed folding curtains, pop-up roof and rear cabinet engine.",
    colorTheme: "bg-red-400 border-white",
    imagePrompt: "minivan"
  },
  {
    id: "21325",
    name: "Medieval Blacksmith",
    year: 2021,
    theme: "Ideas",
    piece_count: 2164,
    minifigure_count: 4,
    hint: "Recreate a highly authentic, multi-story active workshop, complete with a glowing light-brick forge.",
    colorTheme: "bg-stone-600 border-amber-900",
    imagePrompt: "house"
  },
  {
    id: "10295",
    name: "Porsche 911",
    year: 2021,
    theme: "Creator Expert",
    piece_count: 1458,
    minifigure_count: 0,
    hint: "Features options to build either the iconic turbocharged Turbo model or the open-top Targa with removable roof.",
    colorTheme: "bg-white border-neutral-200",
    imagePrompt: "car"
  },
  {
    id: "75313",
    name: "AT-AT",
    year: 2021,
    theme: "Star Wars",
    piece_count: 6785,
    minifigure_count: 9,
    hint: "An incredibly detailed, massive grey quadruped Walker from Star Wars, built with fully functional posing legs.",
    colorTheme: "bg-[#d8dadb] border-slate-400",
    imagePrompt: "quadruped"
  },
  {
    id: "10318",
    name: "Concorde",
    year: 2023,
    theme: "Icons",
    piece_count: 2083,
    minifigure_count: 0,
    hint: "Recreate the world's most famous supersonic passenger aircraft, complete with delta wings and droop-nose design.",
    colorTheme: "bg-slate-50 border-neutral-300",
    imagePrompt: "airplane"
  },
  {
    id: "21343",
    name: "Viking Village",
    year: 2023,
    theme: "Ideas",
    piece_count: 2103,
    minifigure_count: 4,
    hint: "Features interconnected detailed sections with a classic blacksmith shop, chieftain's longhouse and watchtower.",
    colorTheme: "bg-amber-700 border-amber-800",
    imagePrompt: "settlement"
  },
  {
    id: "77015",
    name: "Temple of the Golden Idol",
    year: 2023,
    theme: "Indiana Jones",
    piece_count: 1545,
    minifigure_count: 4,
    hint: "Features interactive dial traps to trigger Indiana Jones escaping a massive rolling boulder trap.",
    colorTheme: "bg-stone-800 border-stone-900",
    imagePrompt: "cave"
  },
  {
    id: "10326",
    name: "Natural History Museum",
    year: 2023,
    theme: "Modular Buildings",
    piece_count: 4014,
    minifigure_count: 7,
    hint: "The first double-width modular building, structured in stunning olive-green bricks, housing skeleton exhibits.",
    colorTheme: "bg-emerald-900 border-stone-700",
    imagePrompt: "museum"
  },
  {
    id: "10278",
    name: "Police Station",
    year: 2021,
    theme: "Modular Buildings",
    piece_count: 2923,
    minifigure_count: 5,
    hint: "Features a three-story municipal office adjoining a cozy retro sweet-donut bakery boutique.",
    colorTheme: "bg-amber-50 border-orange-200",
    imagePrompt: "station"
  },
  {
    id: "10297",
    name: "Boutique Hotel",
    year: 2022,
    theme: "Modular Buildings",
    piece_count: 3066,
    minifigure_count: 7,
    hint: "A complex architectural masterpiece with triangular design mimicking early 20th century European hotels.",
    colorTheme: "bg-stone-100 border-emerald-200",
    imagePrompt: "hotel"
  },
  {
    id: "21326",
    name: "Winnie the Pooh",
    year: 2021,
    theme: "Ideas",
    piece_count: 1265,
    minifigure_count: 5,
    hint: "Pooh Bear's treehouse nestled in the heart of the magical Hundred Acre Wood, featuring honey pots.",
    colorTheme: "bg-yellow-100 border-[#f57f17]",
    imagePrompt: "treehouse"
  },
  {
    id: "10280",
    name: "Flower Bouquet",
    year: 2021,
    theme: "Botanical Collection",
    piece_count: 756,
    minifigure_count: 0,
    hint: "Durable design showing realistic colorful plastic custom roses, snapdragons, and beautiful greenery foliage.",
    colorTheme: "bg-rose-400 border-green-400",
    imagePrompt: "flowers"
  },
  {
    id: "10303",
    name: "Loop Coaster",
    year: 2022,
    theme: "Icons",
    piece_count: 3756,
    minifigure_count: 11,
    hint: "Recreate a mind-boggling vertical roller coaster with a fully functional elevators and two loops.",
    colorTheme: "bg-[#ffe176] border-amber-500",
    imagePrompt: "loop"
  },
  {
    id: "76191",
    name: "Infinity Gauntlet",
    year: 2021,
    theme: "Marvel",
    piece_count: 590,
    minifigure_count: 0,
    hint: "An iconic gold-plated display glove boasting posable fingers and six colored Cosmic Infinity Stones.",
    colorTheme: "bg-amber-400 border-[#caa802]",
    imagePrompt: "glove"
  },
  {
    id: "21309",
    name: "NASA Apollo Saturn V",
    year: 2017,
    theme: "Ideas",
    piece_count: 1969,
    minifigure_count: 0,
    hint: "This majestic one-meter-tall model has exactly 1969 pieces, matching the modern historic lunar voyage year.",
    colorTheme: "bg-slate-50 border-slate-900",
    imagePrompt: "rocket"
  },
  {
    id: "71040",
    name: "Disney Castle",
    year: 2016,
    theme: "Disney",
    piece_count: 4080,
    minifigure_count: 5,
    hint: "Recreate Walt Disney World's magical glass-dome fortress, including Mickey, Minnie and fairy wings components.",
    colorTheme: "bg-blue-300 border-amber-100",
    imagePrompt: "palace"
  }
];
